//! Integration tests for the agent loop and event processing pipeline.
//!
//! These tests use a deterministic mock LLM provider to verify the full
//! Event → LLM → Sandbox → SkillExecutor → Response chain without real API calls.

use std::sync::Arc;
use tokio::sync::Mutex;

use async_trait::async_trait;
use kittypaw_core::config::Config;
use kittypaw_core::error::Result;
use kittypaw_core::types::{Event, EventType, LlmMessage};
use kittypaw_llm::provider::{LlmProvider, LlmResponse};
use kittypaw_sandbox::Sandbox;
use kittypaw_store::Store;

// ── Mock LLM Provider ──────────────────────────────────────────────────

/// A mock provider that returns pre-determined JS code as if generated by an LLM.
struct MockJsProvider {
    js_code: String,
}

impl MockJsProvider {
    fn new(js: &str) -> Self {
        Self {
            js_code: js.to_string(),
        }
    }
}

#[async_trait]
impl LlmProvider for MockJsProvider {
    async fn generate(&self, _messages: &[LlmMessage]) -> Result<LlmResponse> {
        Ok(LlmResponse::text_only(self.js_code.clone()))
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn test_config() -> Config {
    let mut config = Config::default();
    config.freeform_fallback = true; // allow natural language → agent_loop
    config
}

fn telegram_event(text: &str, chat_id: &str) -> Event {
    Event {
        event_type: EventType::Telegram,
        payload: serde_json::json!({
            "text": text,
            "chat_id": chat_id,
            "from_name": "test_user",
        }),
    }
}

fn desktop_event(text: &str) -> Event {
    Event {
        event_type: EventType::Desktop,
        payload: serde_json::json!({
            "text": text,
            "workspace_id": "test",
        }),
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

/// Agent loop processes a simple return statement and produces output.
#[tokio::test]
async fn test_agent_loop_simple_return() {
    let provider = MockJsProvider::new(r#"return "hello from agent";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = desktop_event("say hello");
    let result = session.run(event).await;
    assert!(result.is_ok(), "agent_loop should succeed: {:?}", result);
    assert_eq!(result.unwrap(), "hello from agent");
}

/// Agent loop handles Storage.get/set skill calls within sandbox execution.
#[tokio::test]
async fn test_agent_loop_storage_round_trip() {
    let provider = MockJsProvider::new(
        r#"
        await Storage.set("greeting", "world");
        const val = await Storage.get("greeting");
        return "stored: " + (val && val.value ? val.value : JSON.stringify(val));
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("store something")).await;
    assert!(result.is_ok(), "storage round-trip: {:?}", result);
    let text = result.unwrap();
    // Storage.get now returns a parsed JS object {value: "world"} (auto-parse)
    assert!(
        text.contains("world"),
        "expected stored value containing 'world', got: {text}"
    );
}

/// Agent loop creates a session/agent state that persists across calls.
#[tokio::test]
async fn test_agent_session_state_persists() {
    let provider = MockJsProvider::new(r#"return "ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    // First call creates state
    let r1 = session.run(desktop_event("first")).await;
    assert!(r1.is_ok());

    // Second call reuses state — agent should have 2 user turns + 2 assistant turns
    let r2 = session.run(desktop_event("second")).await;
    assert!(r2.is_ok());

    // Verify state was persisted
    let s = store.lock().await;
    let state = s
        .load_state("desktop-test")
        .expect("load_state")
        .expect("state should exist");
    // 2 user turns + 2 assistant turns = 4 total
    assert!(
        state.turns.len() >= 4,
        "expected >= 4 turns, got {}",
        state.turns.len()
    );
}

/// Telegram events use chat_id as agent_id prefix.
#[tokio::test]
async fn test_telegram_event_creates_agent_id() {
    let provider = MockJsProvider::new(r#"return "tg ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = telegram_event("hello", "12345");
    let result = session.run(event).await;
    assert!(result.is_ok());

    let s = store.lock().await;
    let state = s.load_state("telegram-12345").expect("load_state");
    assert!(state.is_some(), "telegram agent state should be created");
}

/// Bootstrap parity: Config::default() produces a valid config that
/// AgentSession can use without panicking.
#[tokio::test]
async fn test_bootstrap_parity_default_config() {
    let config = Config::default();

    // Verify essential fields have sane defaults
    assert!(config.sandbox.timeout_secs > 0);
    assert!(config.sandbox.memory_limit_mb > 0);
    assert!(config.sandbox.allowed_paths.is_empty()); // backward compat: no restrictions
    assert!(config.agents.is_empty());
    assert!(config.channels.is_empty());

    // Verify Store can be opened with in-memory path
    let store = Store::open(":memory:");
    assert!(store.is_ok(), "in-memory store should open");

    // Verify Sandbox can be created from config
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    // Simple execution should work without panicking
    let result = sandbox.execute("return 42;", serde_json::json!({})).await;
    assert!(result.is_ok(), "sandbox should execute: {:?}", result);
}

/// When freeform_fallback is false, non-slash messages without a matching
/// skill trigger return a helpful message instead of invoking the LLM.
#[tokio::test]
async fn test_freeform_fallback_disabled() {
    let provider = MockJsProvider::new(r#"return "should not reach";"#);
    let mut config = test_config();
    config.freeform_fallback = false;
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store,
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("hello")).await;
    assert!(result.is_ok());
    let text = result.unwrap();
    assert!(
        text.contains("스킬") || text.contains("teach"),
        "should suggest /teach, got: {text}"
    );
}

/// LLM returning invalid JS causes graceful retry/failure, not a panic.
#[tokio::test]
async fn test_agent_loop_handles_invalid_js() {
    let provider = MockJsProvider::new("this is not valid javascript {{{}}}");
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    // Should not panic — may return error or empty string after retries
    let result = session.run(desktop_event("do something")).await;
    // The agent loop retries 3 times with the same broken JS, then returns an error
    assert!(
        result.is_err(),
        "invalid JS should eventually error, not panic"
    );
}

// ── Phase 9: MemoryProvider integration ────────────────────────────────

/// Memory.save + Memory.recall work end-to-end through the agent loop.
#[tokio::test]
async fn test_memory_save_and_recall() {
    let provider = MockJsProvider::new(
        r#"
        await Memory.save("fav_city", "Seoul");
        const memories = await Memory.recall("fav");
        return JSON.stringify(memories);
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("remember my city")).await;
    assert!(result.is_ok(), "memory save+recall: {:?}", result);
    let text = result.unwrap();
    assert!(
        text.contains("Seoul"),
        "expected recalled value 'Seoul', got: {text}"
    );
}

/// Memory.search returns FTS5 results from pre-seeded execution history.
#[tokio::test]
async fn test_memory_search_fts5() {
    let provider = MockJsProvider::new(
        r#"
        const hits = await Memory.search("브리핑");
        return JSON.stringify(hits);
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    // Pre-seed execution history for FTS5
    {
        let s = store.lock().await;
        s.record_execution(
            "weather",
            "날씨 브리핑",
            "2026-04-07T09:00:00Z",
            "2026-04-07T09:00:01Z",
            500,
            "서울 12도 맑음",
            true,
            0,
            None,
            None,
        )
        .unwrap();
    }

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("search memories")).await;
    assert!(result.is_ok(), "memory search: {:?}", result);
    let text = result.unwrap();
    assert!(
        text.contains("날씨 브리핑") || text.contains("브리핑"),
        "expected FTS5 hit, got: {text}"
    );
}

// ── Phase 10: Checkpoint/Rollback integration ─────────────────────────

/// Checkpoint and rollback correctly restores conversation state.
#[tokio::test]
async fn test_checkpoint_and_rollback() {
    let provider = MockJsProvider::new(r#"return "ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    // Run 2 events to build conversation state
    session.run(desktop_event("msg-1")).await.unwrap();
    session.run(desktop_event("msg-2")).await.unwrap();

    let agent_id = "desktop-test";

    // Create checkpoint
    let checkpoint_id = {
        let s = store.lock().await;
        s.create_checkpoint(agent_id, "before-experiment").unwrap()
    };

    // Run 2 more events
    session.run(desktop_event("msg-3")).await.unwrap();
    session.run(desktop_event("msg-4")).await.unwrap();

    // Verify 4 user turns exist (each event adds 1 user + 1 assistant turn)
    {
        let s = store.lock().await;
        let state = s.load_state(agent_id).unwrap().unwrap();
        assert!(
            state.turns.len() >= 8,
            "expected >= 8 turns (4 user + 4 assistant), got {}",
            state.turns.len()
        );
    }

    // Rollback to checkpoint
    let deleted = {
        let s = store.lock().await;
        s.rollback_to_checkpoint(checkpoint_id).unwrap()
    };
    assert!(
        deleted >= 4,
        "should delete at least 4 turns, deleted {deleted}"
    );

    // Verify only first 2 events' turns remain
    {
        let s = store.lock().await;
        let state = s.load_state(agent_id).unwrap().unwrap();
        assert!(
            state.turns.len() <= 4,
            "after rollback expected <= 4 turns, got {}",
            state.turns.len()
        );
    }
}

/// Rollback cascades: later checkpoints are removed.
#[tokio::test]
async fn test_checkpoint_rollback_cascade() {
    let provider = MockJsProvider::new(r#"return "ok";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let agent_id = "desktop-test";
    session.run(desktop_event("a")).await.unwrap();

    let cp1 = {
        let s = store.lock().await;
        s.create_checkpoint(agent_id, "cp-1").unwrap()
    };

    session.run(desktop_event("b")).await.unwrap();

    let _cp2 = {
        let s = store.lock().await;
        s.create_checkpoint(agent_id, "cp-2").unwrap()
    };

    // Rollback to cp1 should also remove cp2
    {
        let s = store.lock().await;
        s.rollback_to_checkpoint(cp1).unwrap();
        let cps = s.list_checkpoints(agent_id).unwrap();
        assert_eq!(cps.len(), 1, "only cp1 should remain, got {}", cps.len());
        assert_eq!(cps[0].id, cp1);
    }
}

// ── Phase 11: Security integration ────────────────────────────────────

/// Secrets in LLM output are masked before being returned.
#[tokio::test]
async fn test_secrets_masked_in_output() {
    let provider =
        MockJsProvider::new(r#"return "my key is sk-abc123def456ghi789jkl012mno345pqr67890";"#);
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("show me the key")).await;
    assert!(result.is_ok(), "should succeed: {:?}", result);
    let text = result.unwrap();
    assert!(
        text.contains("***MASKED***"),
        "secret should be masked, got: {text}"
    );
    assert!(
        !text.contains("sk-abc123def456"),
        "raw secret should NOT appear, got: {text}"
    );
}

/// Dangerous code patterns are logged to audit (scan runs but doesn't block).
#[tokio::test]
async fn test_dangerous_code_audit_logged() {
    // This JS contains a dangerous Shell.exec("rm -rf") pattern.
    // The code scan detects it and logs to audit, but execution proceeds
    // (Shell.exec will fail in sandbox since it's not wired for this test).
    let provider = MockJsProvider::new(
        r#"
        try {
            Shell.exec("rm -rf /tmp/test");
        } catch(e) {}
        return "attempted";
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("clean up")).await;
    // Execution may succeed or fail (Shell.exec may not resolve), but shouldn't panic
    // The important thing is the dangerous pattern was detected — verified by scan_code
    let code = r#"Shell.exec("rm -rf /tmp/test")"#;
    let warnings = kittypaw_engine::security::scan_code(code);
    assert!(!warnings.is_empty(), "dangerous pattern should be detected");
    assert!(
        warnings[0].contains("rm -rf"),
        "warning should mention rm -rf, got: {:?}",
        warnings
    );

    // If execution succeeded, output should exist
    if let Ok(text) = result {
        assert!(
            text.contains("attempted") || text.contains("error"),
            "output: {text}"
        );
    }
}

// ── Web.search Tavily backend integration ─────────────────────────────

/// Web.search with Tavily backend returns real results (requires TAVILY_API_KEY secret).
/// This test calls the actual Tavily API — skip if no key configured.
#[tokio::test]
async fn test_web_search_tavily_real_results() {
    // Check if Tavily key is available
    let tavily_key = kittypaw_core::secrets::get_secret("search", "tavily_api_key")
        .ok()
        .flatten()
        .filter(|k| !k.is_empty());
    if tavily_key.is_none() {
        // CI에서는 키 없이 스킵. 로컬에서는 ~/.kittypaw/secrets.json에 설정 필요.
        return;
    }
    let _key = tavily_key.unwrap(); // 키 존재 확인됨

    let provider = MockJsProvider::new(
        r#"
        const results = await Web.search("artificial intelligence news");
        if (!results || !results.results || results.results.length === 0) {
            return "EMPTY";
        }
        return "FOUND:" + results.results.length + ":" + results.results[0].title;
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let result = session.run(desktop_event("search test")).await;
    assert!(result.is_ok(), "web search should succeed: {:?}", result);
    let text = result.unwrap();
    eprintln!("Web.search result: {text}");
    assert!(
        text.starts_with("FOUND:"),
        "expected real results starting with FOUND:, got: {text}"
    );
}

// ── Telegram agent_loop: Skill.create + sendMessage ─────────────────

/// Telegram event with code that calls Skill.create should not crash.
/// This reproduces the "Exception generated by QuickJS" bug from serve.
#[tokio::test]
async fn test_telegram_skill_create_no_crash() {
    let provider = MockJsProvider::new(
        r#"
        await Skill.create("test-news", "AI 뉴스 요약", "return 'hello';", "schedule", "every 10m");
        await Telegram.sendMessage("54076829", "✅ 스킬 생성 완료!");
        return null;
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = telegram_event("AI 뉴스 10분마다 요약해줘", "54076829");
    let result = session.run(event).await;
    // Should not return an error — even if Telegram API fails, the sandbox
    // should handle it gracefully instead of throwing an unhandled Exception.
    assert!(
        result.is_ok(),
        "telegram skill create should not crash: {:?}",
        result
    );
}

/// Telegram event with Web.search + sendMessage should succeed or
/// degrade gracefully — never throw an unhandled QuickJS Exception.
#[tokio::test]
async fn test_telegram_web_search_and_send_no_crash() {
    let provider = MockJsProvider::new(
        r#"
        try {
            const results = await Web.search("AI news");
            const summary = results && results.results
                ? results.results.map(r => r.title).join("\n")
                : "뉴스를 가져올 수 없습니다";
            await Telegram.sendMessage("54076829", summary);
            return null;
        } catch(e) {
            return "error: " + e.message;
        }
        "#,
    );
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };

    let event = telegram_event("AI 뉴스 알려줘", "54076829");
    let result = session.run(event).await;
    assert!(
        result.is_ok(),
        "web search + telegram send should not crash: {:?}",
        result
    );
}

// ── Schedule loop: skill execution with resolver ────────────────────

/// Scheduled skill that calls Http.get should succeed — the schedule loop
/// must use execute_with_resolver, not bare execute.
/// This reproduces the "Exception generated by QuickJS" bug in schedule.rs.
#[tokio::test]
async fn test_scheduled_skill_with_http_uses_resolver() {
    // Simulate what schedule.rs does: wrap code and execute in sandbox
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());

    let js_code = r#"
        try {
            const resp = await Http.get("https://httpbin.org/get");
            return "status:" + (resp && resp.status ? resp.status : "no-resolver");
        } catch(e) {
            return "error:" + e.message;
        }
    "#;
    let context = serde_json::json!({
        "event_type": "schedule",
        "event_text": "",
        "chat_id": "",
        "skill_name": "test-skill",
    });
    let wrapped = format!("const ctx = JSON.parse(__context__);\n{js_code}");

    // This is what schedule.rs currently does — bare execute without resolver.
    // It should succeed (not throw Exception), even if Http.get returns null.
    let result = sandbox.execute(&wrapped, context).await;
    assert!(result.is_ok(), "sandbox should not error: {:?}", result);
    let exec = result.unwrap();
    // The key assertion: execution must succeed (no unhandled Exception)
    assert!(
        exec.success,
        "scheduled skill should not crash on Http.get. success={}, error={:?}, output={}",
        exec.success, exec.error, exec.output
    );
}

// ── Skill lifecycle: create → list → schedule ───────────────────────

/// Full skill lifecycle: Skill.create saves file with cron, Skill.list returns it.
#[tokio::test]
async fn test_skill_create_and_list_lifecycle() {
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    // Use a unique temp dir for skills so we don't pollute real data
    let tmp_dir = std::env::temp_dir().join(format!("kp-test-skills-{}", std::process::id()));
    let skills_dir = tmp_dir.join(".kittypaw/skills");
    std::fs::create_dir_all(&skills_dir).unwrap();

    // Step 1: Create a skill with schedule
    let create_provider = MockJsProvider::new(
        r#"
        await Skill.create("test-news", "테스트 뉴스 10분마다", `
            const r = await Web.search("news");
            return r;
        `, "schedule", "every 10m");
        return "created";
        "#,
    );
    let session = kittypaw_cli::agent_loop::AgentSession {
        provider: &create_provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };
    let result = session
        .run(telegram_event("뉴스 스킬 만들어줘", "12345"))
        .await;
    assert!(result.is_ok(), "skill create should succeed: {:?}", result);

    // Step 2: Verify skill file was saved
    let skills = kittypaw_core::skill::load_all_skills().unwrap_or_default();
    let found = skills.iter().find(|(s, _)| s.name == "test-news");
    assert!(found.is_some(), "skill 'test-news' should be saved on disk");
    let (skill, _) = found.unwrap();
    assert_eq!(skill.trigger.trigger_type, "schedule");
    assert!(
        skill.trigger.cron.is_some(),
        "cron field must exist, got: {:?}",
        skill.trigger
    );
    assert!(skill.enabled, "skill should be enabled");

    // Step 3: Skill.list should return the skill
    let list_provider = MockJsProvider::new(
        r#"
        const skills = await Skill.list();
        if (!skills || skills.length === 0) return "EMPTY";
        const s = skills.find(x => x.name === "test-news");
        if (!s) return "NOT_FOUND";
        return "FOUND:" + s.triggerType + ":" + s.triggerValue;
        "#,
    );
    let session2 = kittypaw_cli::agent_loop::AgentSession {
        provider: &list_provider,
        fallback_provider: None,
        sandbox: &sandbox,
        store: store.clone(),
        config: &config,
        on_token: None,
        on_permission_request: None,
    };
    let result2 = session2.run(telegram_event("스킬 목록", "12345")).await;
    assert!(result2.is_ok(), "skill list should succeed: {:?}", result2);
    let text = result2.unwrap();
    assert!(
        text.starts_with("FOUND:schedule:"),
        "Skill.list should find test-news with schedule trigger, got: {text}"
    );

    // Cleanup
    let _ = kittypaw_core::skill::delete_skill("test-news");
    let _ = std::fs::remove_dir_all(&tmp_dir);
}

/// Scheduled skill WITHOUT try/catch that calls Http.get — bare execute
/// (without resolver) crashes with "Exception generated by QuickJS".
/// With resolver, it should succeed.
#[tokio::test]
async fn test_scheduled_skill_bare_http_no_trycatch() {
    let config = test_config();
    let sandbox = Sandbox::new_threaded(config.sandbox.clone());
    let store = Arc::new(Mutex::new(
        Store::open(":memory:").expect("in-memory store"),
    ));

    // No try/catch — this is what causes "Exception generated by QuickJS"
    let js_code = r#"
        const resp = await Http.get("https://httpbin.org/get");
        return "status:" + resp.status;
    "#;
    let context = serde_json::json!({
        "event_type": "schedule",
        "event_text": "",
        "chat_id": "",
    });
    let wrapped = format!("const ctx = JSON.parse(__context__);\n{js_code}");

    // Step 1: bare execute WITHOUT resolver — must fail (this was the bug)
    let bare_result = sandbox.execute(&wrapped, context.clone()).await;
    assert!(bare_result.is_ok());
    let bare_exec = bare_result.unwrap();
    assert!(
        !bare_exec.success,
        "bare execute without resolver SHOULD fail (null.status)"
    );

    // Step 2: execute WITH resolver — must succeed (the fix)
    let config_clone = config.clone();
    let store_clone = Arc::clone(&store);
    let resolver: kittypaw_sandbox::SkillResolver =
        std::sync::Arc::new(move |call: kittypaw_core::types::SkillCall| {
            let config = config_clone.clone();
            let store = Arc::clone(&store_clone);
            Box::pin(async move {
                kittypaw_engine::skill_executor::resolve_skill_call(
                    &call, &config, &store, None, None,
                )
                .await
            })
        });

    let resolved_result = sandbox
        .execute_with_resolver(&wrapped, context, Some(resolver))
        .await;
    assert!(
        resolved_result.is_ok(),
        "sandbox with resolver should not error: {:?}",
        resolved_result
    );
    let resolved_exec = resolved_result.unwrap();
    assert!(
        resolved_exec.success,
        "with resolver, Http.get should work. error={:?}, output={}",
        resolved_exec.error, resolved_exec.output
    );
}

// ── Reflection tests ───────────────────────────────────────────────────

/// Mock provider that returns a fixed JSON string (for reflection intent grouping).
struct MockJsonProvider {
    response: String,
}

impl MockJsonProvider {
    fn new(json: &str) -> Self {
        Self {
            response: json.to_string(),
        }
    }
}

#[async_trait]
impl LlmProvider for MockJsonProvider {
    async fn generate(&self, _messages: &[LlmMessage]) -> Result<LlmResponse> {
        Ok(LlmResponse::text_only(self.response.clone()))
    }
}

/// Reflection: 3 similar messages → suggestion created → reject → re-run filters it.
#[tokio::test]
async fn test_reflection_full_pipeline() {
    let store = Store::open(":memory:").expect("in-memory store");

    // Insert 3 user messages with current timestamps
    store
        .save_state(&kittypaw_core::types::AgentState::new("r1", "sys"))
        .unwrap();
    for msg in &["환율 알려줘", "달러 가격 얼마야", "환율 얼마야"] {
        store
            .add_turn(
                "r1",
                &kittypaw_core::types::ConversationTurn {
                    role: kittypaw_core::types::Role::User,
                    content: msg.to_string(),
                    code: None,
                    result: None,
                    // Use far-future timestamp so it's always "within 24h" relative to now
                    timestamp: "2099-01-01 00:00:00".to_string(),
                },
            )
            .unwrap();
    }

    let mock = MockJsonProvider::new(
        r#"{"groups":[{"intent_label":"환율 조회","messages":["환율 알려줘","달러 가격 얼마야","환율 얼마야"],"count":3}]}"#,
    );

    let config = kittypaw_core::config::ReflectionConfig {
        enabled: true,
        cron: "0 0 3 * * *".into(),
        max_input_chars: 4000,
        intent_threshold: 3,
        ttl_days: 7,
    };

    // Run reflection
    let result = kittypaw_engine::reflection::run_reflection(&store, &mock, &config)
        .await
        .unwrap();

    assert_eq!(
        result.suggestions.len(),
        1,
        "should detect 1 repeated intent"
    );
    assert!(result.suggestions[0].intent_label.contains("환율"));
    let hash = result.suggestions[0].intent_hash.clone();

    // Verify suggest_candidate was stored
    let candidate = store
        .get_user_context(&format!("suggest_candidate:{hash}"))
        .unwrap();
    assert!(candidate.is_some(), "candidate should be in user_context");
    assert!(
        candidate.unwrap().contains("환율 조회"),
        "candidate value should contain intent label"
    );

    // Verify reflection:intent was stored (for Learned Patterns)
    let intent = store
        .get_user_context(&format!("reflection:intent:{hash}"))
        .unwrap();
    assert!(intent.is_some(), "reflection intent should be stored");

    // Re-run: should NOT create duplicate suggestion
    let result2 = kittypaw_engine::reflection::run_reflection(&store, &mock, &config)
        .await
        .unwrap();
    assert_eq!(
        result2.suggestions.len(),
        0,
        "should skip already-suggested intent"
    );

    // Reject the suggestion
    store
        .set_user_context(&format!("rejected_intent:{hash}"), "환율 조회", "user")
        .unwrap();
    // Clear the candidate (simulating CLI reject)
    store
        .set_user_context(&format!("suggest_candidate:{hash}"), "", "rejected")
        .unwrap();

    // Re-run with a new mock that still returns the same group
    let mock3 = MockJsonProvider::new(
        r#"{"groups":[{"intent_label":"환율 조회","messages":["환율"],"count":3}]}"#,
    );
    let result3 = kittypaw_engine::reflection::run_reflection(&store, &mock3, &config)
        .await
        .unwrap();
    assert_eq!(
        result3.suggestions.len(),
        0,
        "rejected intent should never be suggested again"
    );
}

/// Reflection: memory_context_lines includes Learned Patterns section.
#[tokio::test]
async fn test_reflection_learned_patterns_in_context() {
    use kittypaw_core::memory::MemoryProvider;

    let store = Store::open(":memory:").expect("in-memory store");

    // Store a reflection intent
    store
        .set_user_context("reflection:intent:abc123", "환율 조회", "reflection")
        .unwrap();

    let lines = store.memory_context_lines().unwrap();
    let joined = lines.join("\n");

    assert!(
        joined.contains("Learned Patterns"),
        "should have Learned Patterns section"
    );
    assert!(
        joined.contains("환율 조회"),
        "should contain the intent label"
    );

    // reflection keys should NOT appear in Remembered Facts
    if joined.contains("Remembered Facts") {
        assert!(
            !joined.contains("reflection:intent:"),
            "raw reflection keys should not leak into Remembered Facts"
        );
    }
}
